"""add bill file metafile

Revision ID: 39558bbd452a
Revises: 67cfb1e9aef9
Create Date: 2026-09-14 16:25:17.298239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39558bbd452a'
down_revision: Union[str, Sequence[str], None] = '67cfb1e9aef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_bills', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('energy_bills', sa.Column('stored_filename', sa.String(length=255), nullable=True))
    op.add_column('energy_bills', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('energy_bills', sa.Column('content_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('energy_bills', 'content_type')
    op.drop_column('energy_bills', 'file_path')
    op.drop_column('energy_bills', 'stored_filename')
    op.drop_column('energy_bills', 'original_filename')
    # ### end Alembic commands ###
