"""Add customers and link bills

Revision ID: 4f058e9f87dc
Revises: 68ff4f50ba78
Create Date: 2026-09-16 13:27:30.665651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f058e9f87dc'
down_revision: Union[str, Sequence[str], None] = '68ff4f50ba78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
                    sa.Column(
                        'id',
                        sa.Integer(),
                        sa.Identity(),
                        nullable=False,
                    ),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile')
    )
    op.add_column('energy_bills', sa.Column('customer_id', sa.Integer(), nullable=True))
    connection = op.get_bind()
    connection.execute(sa.text("""
            INSERT INTO customers (name)
            SELECT DISTINCT customer_name
            FROM energy_bills
            WHERE customer_name IS NOT NULL
        """))

    connection.execute(
        sa.text("""
            UPDATE energy_bills AS eb
            SET customer_id = c.id
            FROM customers AS c
            WHERE eb.customer_name = c.name
        """)
    )
    op.create_foreign_key("fk_energy_bills_customer_id", 'energy_bills', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_energy_bills_customer_id", 'energy_bills', type_='foreignkey')
    op.drop_column('energy_bills', 'customer_id')
    op.drop_table('customers')
    # ### end Alembic commands ###
