"""Add etracted energy bill columns

Revision ID: 68ff4f50ba78
Revises: 9fef755e607f
Create Date: 2026-09-15 11:55:09.863383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ff4f50ba78'
down_revision: Union[str, Sequence[str], None] = '9fef755e607f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_bills', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('energy_bills', sa.Column('electricity_meter_number', sa.String(length=255), nullable=True))
    op.add_column('energy_bills', sa.Column('previous_meter_reading', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('energy_bills', sa.Column('current_meter_reading', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('energy_bills', sa.Column('electricity_charges', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('energy_bills', sa.Column('water_charges', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('energy_bills', sa.Column('service_charges', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('energy_bills', sa.Column('vat', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('energy_bills', sa.Column('payment_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('energy_bills', 'payment_status')
    op.drop_column('energy_bills', 'vat')
    op.drop_column('energy_bills', 'service_charges')
    op.drop_column('energy_bills', 'water_charges')
    op.drop_column('energy_bills', 'electricity_charges')
    op.drop_column('energy_bills', 'current_meter_reading')
    op.drop_column('energy_bills', 'previous_meter_reading')
    op.drop_column('energy_bills', 'electricity_meter_number')
    op.drop_column('energy_bills', 'due_date')
    # ### end Alembic commands ###
