"""Add bill processing status

Revision ID: 9fef755e607f
Revises: 39558bbd452a
Create Date: 2026-09-14 16:33:40.006043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fef755e607f'
down_revision: Union[str, Sequence[str], None] = '39558bbd452a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_bills', sa.Column('status', sa.String(length=50), nullable=False,server_default='uploaded'))
    op.alter_column('energy_bills', 'customer_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('energy_bills', 'billing_period_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('energy_bills', 'billing_period_end',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('energy_bills', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('energy_bills', 'energy_consumption',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('energy_bills', 'energy_consumption',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.alter_column('energy_bills', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('energy_bills', 'billing_period_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('energy_bills', 'billing_period_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('energy_bills', 'customer_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('energy_bills', 'status')
    # ### end Alembic commands ###
